version: "3.6"
services:
    db:
        image: postgres:12
        command: postgres -c wal_level=logical  -c max_replication_slots=2
        restart: always
        volumes:
            - app-db-data:/var/lib/postgresql/data/pgdata
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        env_file:
            - .env
        ports: 
            - 5432:5432

    pgadmin:
        image: dpage/pgadmin4
        env_file:
            - .env
        ports:
            - "5050:5050"
        volumes:
            - ./:/app
    
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
        environment:
            - "discovery.type=single-node"
        volumes:
            - es_data:/usr/share/elasticsearch/data
        ports: 
            - "9200:9200"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9200"]
            interval: 10s
            timeout: 10s
            retries: 5
    
    kibana:
        image: kibana:7.2.0
        restart: always
        ports: 
            - "5601:5601"
    
    redis:
        image: redis
        command: redis-server --requirepass ninja-password
        
    workspace:
        build: ./workspace
        environment:
            - PGPASSWORD=ninja-password
            - PG_USER=postgres
            - PG_PASSWORD=ninja-password
            - PG_HOST=db
            - PG_PORT=5432
            - ELASTICSEARCH_HOST=elasticsearch
            - REDIS_HOST=redis
            - REDIS_AUTH=ninja-password
        volumes: 
            - ./workspace:/workspace
        ports: 
            - "5000:5000"
        depends_on:
            elasticsearch:
                condition: service_healthy

        

volumes:
    app-db-data:
    es_data: